# Generated by Django 4.2.25 on 2026-04-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpost',
            name='category',
            field=models.CharField(choices=[('story', 'Story'), ('guide', 'Guide'), ('experience', 'Experience')], default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelpost',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='travelpost',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='travel/'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
